function hrtf_list = load_hrtf_list(hrtf_list)
%IMPORTFILE Import data from a text file
%  FILENAME = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  FILENAME = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  filename = importfile("C:\Users\rbarumerli\repos\datasets\hrtfs\lap-task1-hrtfs\filename.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Jul-2024 10:23:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["collection", "sofa"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "sofa", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["collection", "sofa"], "EmptyFieldRule", "auto");

% Import the data
hrtf_list = readtable(hrtf_list, opts);

hrtf_list = table2cell(hrtf_list);
numIdx = cellfun(@(x) ~isnan(str2double(x)), hrtf_list);
hrtf_list(numIdx) = cellfun(@(x) {str2double(x)}, hrtf_list(numIdx));
end